version: '3'

services:
  stubby:
    image: "cuongtransc/stubby"
    build: stubby
    networks:
     - dns
    restart: unless-stopped

  unbound:
    image: "cuongtransc/unbound:1.8.3-stubby"
    build: unbound
    depends_on:
      - "stubby"
    ports:
     - "53:53/udp"
    networks:
     - dns
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  dns:
